name: tf-visualizer-action-test
on:
  pull_request:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: pull_request
        run: echo ${{github.event.pull_request.url}}
      - name: Hello world action step
        id: hello
        uses: fatihtokus/tf-visualizer-action@v0.0.14
        with:
          pull-request: ${{github.event.pull_request.url}}
          github-token: ${{ github.token }}
