name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'json'
          output: 'trivy.json'
          exit-code: '1'
          ignore-unfixed: true          
      - name: Upload math result for job 1
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: trivy.json
