name: tf-visualizer-action-test
on:
  pull_request:
jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        id: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
        with:
          working_directory: ''
          tfsec_args: --soft-fail --no-ignores
          github_token: ${{ github.token }}
      - name: Upload math result for job 1
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: tf_results
          path: results.json
      - name: Print the final result
        if: always()
        shell: bash
        run: |
          value=`cat results.json`
          echo The result is $value
              name: A job to say hello
      - name: pull_request
        run: echo ${{github.event.pull_request.url}}
      - name: tf-visualizer-action
        if: always()
        id: hello
        uses: fatihtokus/tf-visualizer-action@v0.0.27
        with:
          pull-request: ${{github.event.pull_request.url}}
          github-token: ${{ github.token }}
      - name: Download math result for job 2
        if: always()
        uses: actions/download-artifact@v3
        with:
          name: tf_results
      - name: outputtest1
        if: always()
        run: |
          ls
          echo "mix-ecto_create='ABC'" >> $GITHUB_OUTPUT
        id: run_tests
      - name: outputtest2
        if: always()
        run: |
          echo ${{steps.run_tests.outputs.mix-ecto_create}}
          echo ${{join(steps.run_tests.outputs.*, '\n')}}
          echo ${{join(steps.tfsec.outputs.*, '\n')}}
#   create_issue:
#     runs-on: ubuntu-latest
#     permissions:
#       issues: write 
#     steps:
#       - name: Create issue using REST API
#         run: |
#           curl --request POST \
#           --url https://api.github.com/repos/${{ github.repository }}/issues \
#           --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
#           --header 'content-type: application/json' \
#           --data '{
#             "title": "Automated issue for commit: ${{ github.sha }}",
#             "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
#             }' \
#           --fail
#   hello_world_job:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       pull-requests: write
#     name: A job to say hello
#     steps:
#       - name: pull_request
#         run: echo ${{github.event.pull_request.url}}
#       - name: Hello world action step
#         id: hello
#         uses: fatihtokus/tf-visualizer-action@v0.0.15
#         with:
#           pull-request: ${{github.event.pull_request.url}}
#           github-token: ${{ github.token }}
