# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      pull_request:
        description: 'Pull request url'
        default: 'https://api.github.com/repos/fatihtokus/tf-visualizer-action-test/pulls/2'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.pull_request }}"
      
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.tfsec.outputs.test }}

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          tfsec_args: --soft-fail
          github_token: ${{ github.token }}
          tfsec_formats: sarif,csv
         
      - name: outputtest
        run: echo ${{steps.tfsec.outputs.results}}
